require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'test/**/*'
    - 'config.ru'
    - 'app/channels/**/*'
    - 'Rakefile'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/*'
    - 'app/controllers/application_controller.rb'
    - 'gemfiles/vendor/bundle/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
  NewCops: enable
  SuggestExtensions: false

Metrics/AbcSize:
  Max: 35
  Enabled: true

Metrics/MethodLength:
  Max: 20
  Enabled: true

RSpec/ExampleLength:
  Max: 20
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10
  Enabled: true